// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qwi.josemi.roo.domain;

import com.qwi.josemi.roo.domain.Login;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Login_Roo_Configurable {
    
    declare @type: Login: @Configurable;
    
}
